name: build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: docker/setup-qemu-action@v2.1.0
      - uses: docker/setup-buildx-action@v2.2.0
      - run: |
          echo $(grep '^ARG LOCI_' Dockerfile | cut -d' ' -f2) >> $GITHUB_ENV
      - uses: docker/login-action@v2
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - uses: docker/build-push-action@v3.2.0
        with:
          context: .
          cache-from: type=registry,ref=quay.io/vexxhost/bindep-loci:latest
          cache-to: type=inline
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            quay.io/vexxhost/bindep-loci:latest
            quay.io/vexxhost/bindep-loci:${{ env.LOCI_SHA1 }}
