name: sync

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: ./tools/bump-loci
      - uses: peter-evans/create-pull-request@v4.2.3
        with:
          commit-message: Automated OpenStack LOCI versions bump
          branch: auto/bump-openstack-loci
          delete-branch: true
          title: Automatic bump of OpenStack LOCI
          body: |
            This is an automatic bump of OpenStack LOCI version in order to
            make sure that we always have the latest images available.  This
            should be merged once all images build successfully.
          assignees: |
            mnaser
          reviewers: |
            mnaser
